config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  resources :sessions
  resources :reset_passwords, only: [:new, :create, :edit, :update], param: :token
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  has_secure_token :reset_password_token

  validates :email, presence: true
  validates :email, uniqueness: true
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

  validates :name, presence: true, length: { minimum: 5 }, on: :update
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user]
      @current_user = User.find_by_id(session[:user])
    else
      @current_user = nil
    end
  end
end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_token, only: :update
  before_action :pwd_check, only: :update

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user.present?
      user.reset_token_expired_at = Time.now + 6.hours
      user.reset_password_token = SecureRandom.urlsafe_base64(nil, false)
      user.save(validate: false)

      ResetPasswordMailer.instruction(user).deliver_now

      flash[:notice] = "Reset instruction sent!"
      redirect_back(fallback_location: new_reset_password_path)
    else
      flash[:error] = "Invlalid Email Address"
      render :new
    end
  end

  def edit
    redirect_to root_url unless @user.present?
  end

  def update
    if @user.errors.any?
      flash[:error] = @user.errors.full_messages
    else
      flash[:notice] = "Password resets"

      @user.password = user_params[:password]
      @user.save(validate: false)
    end

    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation, :reset_token_expired_at)
  end

  def get_user
    @user = User.find_by(reset_password_token: params[:token])
  end

  def valid_token
    unless (@user &&  Time.now < @user.reset_token_expired_at)
      flash[:error] = "Token is invalid or has expired."

      redirect_to root_path
    end
  end

  def pwd_check
    pwd = user_params[:password]
    pwd_conf =user_params[:password_confirmation]

    if pwd.blank?
      @user.errors.add(:password, "can't be empty")
    elsif pwd.length < 8
      @user.errors.add(:password, "should be more than 8 characters")
    elsif pwd_conf != pwd
      @user.errors.add(:password, "should match with Password confirmation")
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to edit_user_path(session[:user]) if current_user
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user] = user.id
      redirect_to edit_user_path(user.id), notice: "Welcome back! #{ user.name }"
    else
      flash[:error] = "Invalid Email or Password"
      render :new
    end
  end

  def destroy
    session[:user] = nil
    redirect_to root_path, notice: "Bye!!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])

    if @user.update_attributes(user_params)
      flash[:notice] = 'Updated'
    else
      flash[:error] = @user.errors.full_messages
    end

    redirect_to edit_user_path(params[:id])
  end

  def new
    redirect_to edit_user_path(session[:user]) if current_user

    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.name = @user.email.split('@').first

    if @user.save
      session[:user] = @user.id

      UsersMailer.welcome(@user).deliver_now

      redirect_to edit_user_path(@user.id), notice: 'Thank you for siging up'
    else
      flash[:error] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:notice].present? %>
  <li><%= flash[:notice] %></li>
<% else %>
  <% if flash[:error].class == Array %>
    <% flash[:error].each do |error_msg| %>
      <li><%= error_msg %></li>
    <% end %>
  <% else %>
    <%= flash[:error] %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IncubitAssessment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% if current_user %>
      <%= button_to "Logout", session_path, method: :delete %>
    <% end %>
  </body>
</html>

app/views/layouts/users/_edit.html.erb
<div class="field">
  <%= form.label :email %><br />
  <%= @user.email %>
</div>
<div class="field">
  <%= form.label :name %><br />
  <%= form.text_field :name %>
</div>

app/views/layouts/users/_new.html.erb
<div class="field">
  <%= form.label :email %><br />
  <%= form.text_field :email %>
</div>

app/views/reset_passwords/edit.html.erb
<h1>Reset Password</h1>
<%= form_for(@user, url: reset_password_path(params[:token])) do |f| %>
  <% if flash.any? %>
    <%= render "layouts/flash", flash: flash %>
  <% end %>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/reset_passwords/new.html.erb
<h1>Forgot Password</h1>
<% if flash.any? %>
  <%= render "layouts/flash", flash: flash %>
<% end %>

<%= form_tag reset_passwords_path do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="actions">
    <%= submit_tag "Submit" %>
  </div>
<% end %>

app/views/users/_form.html.erb
<h1><%= title %></h1>
<%= form_for @user do |f| %>
  <% if flash.any? %>
    <%= render "layouts/flash", flash: flash %>
  <% end %>

  <%= render "layouts/users/#{ action }.html.erb", form: f %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "#{ btn_text }" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render "form",action: 'edit', title: "Edit", btn_text: "Update" %>

app/views/users/new.html.erb
<%= render "form", action: 'new', title: "Sign Up", btn_text: "Sign Up" %>
<%= link_to "Sign In", new_session_path %>